const sendTransaction = async (secret, destination, amount) => {
	try {
		// Here is where the magic happens
	} catch (err) {
		console.error('An error has occurred', err)
	}
}

export default sendTransaction
